spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/billing}
    username: ${SPRING_DATASOURCE_USERNAME:billing}
    password: ${SPRING_DATASOURCE_PASSWORD:billing}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
