spring:
  datasource:
    url: ${PG_MAIN_HOST:jdbc:postgresql://localhost:5432/billing}
    username: ${PG_MAIN_USER:postgres}
    password: ${PG_MAIN_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
