/* =========================================================
                    테이블 셋업
   ========================================================= */
DROP TABLE IF EXISTS user_soldier CASCADE;
DROP TABLE IF EXISTS user_plans CASCADE;
DROP TABLE IF EXISTS user_option_subscription CASCADE;
DROP TABLE IF EXISTS user_contract CASCADE;
DROP TABLE IF EXISTS plan_included_option CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS plan CASCADE;
DROP TABLE IF EXISTS welfare_discount CASCADE;
DROP TABLE IF EXISTS option_service CASCADE;
DROP TABLE IF EXISTS network_type CASCADE;
DROP TABLE IF EXISTS data_billing_type CASCADE;
DROP TABLE IF EXISTS contract_discount CASCADE;
DROP TABLE IF EXISTS monthly_data_usage CASCADE;
DROP TABLE IF EXISTS chennel_alias CASCADE ;

-- 1) 계약(선택약정) 할인 정책
CREATE TABLE contract_discount
(
    discount_percent numeric(5, 4) NOT NULL,
    duration_months  integer       NOT NULL PRIMARY KEY,
    CONSTRAINT ck_contract_discount_percent
        CHECK (discount_percent >= 0 AND discount_percent <= 1)
);

COMMENT ON TABLE contract_discount IS '선택 약정 할인 정책';


-- 2) 무제한 여부 종류
CREATE TABLE data_billing_type
(
    data_billing_type_code varchar(10) NOT NULL PRIMARY KEY,
    data_billing_type_name varchar(50) NOT NULL UNIQUE
);

COMMENT ON TABLE data_billing_type IS '무제한 여부 종류';
COMMENT ON COLUMN data_billing_type.data_billing_type_code IS '무제한 데이터 코드';

-- 3) 네트워크 종류
CREATE TABLE network_type
(
    network_type_code varchar(10) NOT NULL PRIMARY KEY,
    network_type_name varchar(10) NOT NULL
);

COMMENT ON TABLE network_type IS '네트워크 종류';
COMMENT ON COLUMN network_type.network_type_code IS '네트워크 종류 코드';
COMMENT ON COLUMN network_type.network_type_name IS '네트워크 이름';


-- 4) 부가 서비스 종류(코드 테이블)
CREATE TABLE option_service
(
    option_service_code varchar(10) NOT NULL PRIMARY KEY,
    option_service_name varchar(20) NOT NULL UNIQUE,
    monthly_price       bigint      NOT NULL
);

COMMENT ON TABLE option_service IS '부가 서비스 종류';
COMMENT ON COLUMN option_service.option_service_code IS '부가 서비스 종류 식별자';
COMMENT ON COLUMN option_service.option_service_name IS '부가 서비스 종류 이름';


-- 5) 복지 할인 정책(코드 테이블)
CREATE TABLE welfare_discount
(
    discount_rate numeric(5, 4) NOT NULL,
    max_discount  integer,
    welfare_code  varchar(10)   NOT NULL PRIMARY KEY,
    welfare_name  varchar(30)   NOT NULL,
    CONSTRAINT ck_welfare_discount_rate
        CHECK (discount_rate >= 0 AND discount_rate <= 1)
);

COMMENT ON TABLE welfare_discount IS '복지 할인 정책';
COMMENT ON COLUMN welfare_discount.discount_rate IS '할인율';
COMMENT ON COLUMN welfare_discount.max_discount IS '할인 상한액';
COMMENT ON COLUMN welfare_discount.welfare_code IS '복지 할인 정책';
COMMENT ON COLUMN welfare_discount.welfare_name IS '복지 종류';


-- 6) 요금제
CREATE TABLE plan
(
    excess_charge_per_mb   numeric(5, 4) NOT NULL,
    included_data_mb       integer       NOT NULL,
    is_military_eligible   boolean       NOT NULL,
    monthly_price          integer       NOT NULL,
    data_billing_type_code varchar(10)   NOT NULL,
    network_type_code      varchar(10)   NOT NULL,
    plan_code              varchar(10)   NOT NULL PRIMARY KEY,
    name                   varchar(50)   NOT NULL,
    info                   text          NOT NULL,

    CONSTRAINT fk_plan_data_billing_type
        FOREIGN KEY (data_billing_type_code)
            REFERENCES data_billing_type (data_billing_type_code),

    CONSTRAINT fk_plan_network_type
        FOREIGN KEY (network_type_code)
            REFERENCES network_type (network_type_code)
);

COMMENT ON TABLE plan IS '요금제';
COMMENT ON COLUMN plan.excess_charge_per_mb IS '초과 데이터 MB당 요금';
COMMENT ON COLUMN plan.included_data_mb IS '기본 데이터 제공량';
COMMENT ON COLUMN plan.is_military_eligible IS '군인 요금제 여부';
COMMENT ON COLUMN plan.monthly_price IS '월 비용';
COMMENT ON COLUMN plan.data_billing_type_code IS '무제한 데이터 코드';
COMMENT ON COLUMN plan.network_type_code IS '네트워크 종류 코드';
COMMENT ON COLUMN plan.plan_code IS '요금제 식별자';
COMMENT ON COLUMN plan.name IS '요금제 이름';
COMMENT ON COLUMN plan.info IS '요금제 설명';


-- 7) 요금제 기본 제공 서비스(매핑)
CREATE TABLE plan_included_option
(
    plan_option_id      bigint generated by default as identity PRIMARY KEY,
    option_service_code varchar(10) NOT NULL,
    plan_code           varchar(10) NOT NULL,

    CONSTRAINT uk_plan_included_option_plan_option
        UNIQUE (plan_code, option_service_code),

    CONSTRAINT fk_plan_included_option_option_service
        FOREIGN KEY (option_service_code)
            REFERENCES option_service (option_service_code),

    CONSTRAINT fk_plan_included_option_plan
        FOREIGN KEY (plan_code)
            REFERENCES plan (plan_code)
);

COMMENT ON TABLE plan_included_option IS '요금제 기본 제공 서비스';
COMMENT ON COLUMN plan_included_option.plan_option_id IS '요금제 기본 제공 부가 서비스 식별자';
COMMENT ON COLUMN plan_included_option.option_service_code IS '부가 서비스 FK';
COMMENT ON COLUMN plan_included_option.plan_code IS '요금제 FK';


-- 8) 유저
CREATE TABLE users
(
    birth_date   date                        NOT NULL,
    is_welfare   boolean                     NOT NULL default false,
    join_date    date                        NOT NULL,
    created_at   timestamp(6) with time zone NOT NULL,
    modified_at  timestamp(6) with time zone NOT NULL,
    user_id      bigint                      NOT NULL PRIMARY KEY,
    name         varchar(100)                 NOT NULL,
    email        varchar(150)                NOT NULL UNIQUE,
    plan_code    varchar(10),
    welfare_code varchar(10),
    phone_number varchar(150)                 NOT NULL UNIQUE,
    user_role    varchar(255)                NOT NULL,
    from_time    varchar(2)                  NULL,
    to_time      varchar(2)                  NULL,
    day_time     varchar(2)                  NULL
        CONSTRAINT users_user_role_check
            CHECK ((user_role)::text = ANY
                   ((ARRAY ['ADMIN'::character varying, 'GUEST'::character varying, 'USER'::character varying])::text[])),
    user_status  varchar(255)                NOT NULL
        CONSTRAINT users_user_status_check
            CHECK ((user_status)::text = ANY
                   ((ARRAY ['ACTIVE'::character varying, 'WITHDRAWN'::character varying, 'BANNED'::character varying])::text[])),

    CONSTRAINT fk_users_plan
        FOREIGN KEY (plan_code)
            REFERENCES plan (plan_code),

    CONSTRAINT fk_users_welfare_discount
        FOREIGN KEY (welfare_code)
            REFERENCES welfare_discount (welfare_code),

    CONSTRAINT ck_users_time_window
        CHECK (
            from_time ~ '^\d{2}$'
                AND to_time ~ '^\d{2}$'
                AND from_time < to_time
                AND from_time BETWEEN '00' AND '23'
                AND to_time BETWEEN '00' AND '23'
            )
);

COMMENT ON TABLE users IS '유저';
COMMENT ON COLUMN users.birth_date IS '유저 생년월일';
COMMENT ON COLUMN users.is_welfare IS '복지 대상 여부';
COMMENT ON COLUMN users.join_date IS '유저 가입일';
COMMENT ON COLUMN users.created_at IS '유저 생성일';
COMMENT ON COLUMN users.modified_at IS '유저 수정일';
COMMENT ON COLUMN users.user_id IS '유저 식별값';
COMMENT ON COLUMN users.name IS '유저 이름';
COMMENT ON COLUMN users.plan_code IS '요금제 코드';
COMMENT ON COLUMN users.welfare_code IS '복지 할인 코드';
COMMENT ON COLUMN users.phone_number IS '유저 전화번호';
COMMENT ON COLUMN users.user_role IS '유저 권한';
COMMENT ON COLUMN users.user_status IS '유저 상태';


-- 9) 유저 선택 약정
CREATE TABLE user_contract
(
    end_date         date   NOT NULL,
    start_date       date   NOT NULL,
    user_contract_id bigint generated by default as identity PRIMARY KEY,
    user_id          bigint NOT NULL,

    CONSTRAINT ck_user_contract_range
        CHECK (start_date < end_date),

    CONSTRAINT fk_user_contract_user
        FOREIGN KEY (user_id)
            REFERENCES users (user_id)
);

COMMENT ON TABLE user_contract IS '유저 선택 약정';
COMMENT ON COLUMN user_contract.end_date IS '종료일';
COMMENT ON COLUMN user_contract.start_date IS '시작일';
COMMENT ON COLUMN user_contract.user_contract_id IS '유저 선택 약정 식별자';
COMMENT ON COLUMN user_contract.user_id IS '유저 FK';


-- 10) 유저 직접 구독 부가 서비스
CREATE TABLE user_option_subscription
(
    end_date            timestamp(6) with time zone NOT NULL,
    start_date          timestamp(6) with time zone NOT NULL,
    user_id             bigint                      NOT NULL,
    user_option_id      bigint generated by default as identity PRIMARY KEY,
    option_service_code varchar(10)                 NOT NULL,

    CONSTRAINT ck_user_option_subscription_range
        CHECK (start_date < end_date),

    CONSTRAINT fk_user_option_subscription_user
        FOREIGN KEY (user_id)
            REFERENCES users (user_id),

    CONSTRAINT fk_user_option_subscription_option_service
        FOREIGN KEY (option_service_code)
            REFERENCES option_service (option_service_code)
);

COMMENT ON TABLE user_option_subscription IS '유저 직접 구독 부가 서비스';
COMMENT ON COLUMN user_option_subscription.end_date IS '구독 만료일';
COMMENT ON COLUMN user_option_subscription.start_date IS '구독 시작일';
COMMENT ON COLUMN user_option_subscription.user_id IS '유저 FK';
COMMENT ON COLUMN user_option_subscription.user_option_id IS '유저 직접 구독 부가 서비스 식별자';
COMMENT ON COLUMN user_option_subscription.option_service_code IS '부가 서비스 코드';


-- 11) 사용자 요금제(이력)
CREATE TABLE user_plans
(
    end_date     timestamp(6) with time zone NOT NULL,
    start_date   timestamp(6) with time zone NOT NULL,
    user_id      bigint                      NOT NULL,
    user_plan_id bigint generated by default as identity PRIMARY KEY,
    plan_code    varchar(10)                 NOT NULL,

    CONSTRAINT ck_user_plans_range
        CHECK (start_date < end_date),

    CONSTRAINT fk_user_plans_user
        FOREIGN KEY (user_id)
            REFERENCES users (user_id),

    CONSTRAINT fk_user_plans_plan
        FOREIGN KEY (plan_code)
            REFERENCES plan (plan_code)
);

COMMENT ON TABLE user_plans IS '사용자 요금제';
COMMENT ON COLUMN user_plans.end_date IS '요금제 만료일';
COMMENT ON COLUMN user_plans.start_date IS '요금제 가입일';
COMMENT ON COLUMN user_plans.user_id IS '유저 FK';
COMMENT ON COLUMN user_plans.user_plan_id IS '사용자 요금제 식별자';
COMMENT ON COLUMN user_plans.plan_code IS '요금제 코드';


-- 12) 유저 군인 정보
CREATE TABLE user_soldier
(
    end_date        date,
    start_date      date   NOT NULL,
    user_id         bigint NOT NULL UNIQUE,
    user_soldier_id bigint generated by default as identity PRIMARY KEY,

    CONSTRAINT fk_user_soldier_user
        FOREIGN KEY (user_id)
            REFERENCES users (user_id)
);

COMMENT ON COLUMN user_soldier.end_date IS '전역일';
COMMENT ON COLUMN user_soldier.start_date IS '입대일';
COMMENT ON COLUMN user_soldier.user_id IS '유저 FK';
COMMENT ON COLUMN user_soldier.user_soldier_id IS '유저군인 식별자';


-- 13) 사용자 월별 사용량
CREATE TABLE monthly_data_usage
(
    data_usage_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    used_data_mb        BIGINT      NOT NULL,
    usage_aggregated_at TIMESTAMPTZ NOT NULL,

    usage_year_month    VARCHAR(7)  NOT NULL,
    user_id             BIGINT      NOT NULL,

    CONSTRAINT uk_monthly_data_usage_user_month UNIQUE (user_id, usage_year_month)
);

