/* =========================================================
                    테이블 셋업
   ========================================================= */
DROP TABLE IF EXISTS public.family_group_user        CASCADE;
DROP TABLE IF EXISTS public.user_soldier             CASCADE;
DROP TABLE IF EXISTS public.user_plans               CASCADE;
DROP TABLE IF EXISTS public.user_option_subscription CASCADE;
DROP TABLE IF EXISTS public.user_contract            CASCADE;
DROP TABLE IF EXISTS public.plan_included_option     CASCADE;
DROP TABLE IF EXISTS public.option_policy_history    CASCADE;

DROP TABLE IF EXISTS public.users                    CASCADE;

DROP TABLE IF EXISTS public.plan                     CASCADE;

DROP TABLE IF EXISTS public.welfare_discount         CASCADE;
DROP TABLE IF EXISTS public.option_service           CASCADE;
DROP TABLE IF EXISTS public.network_type             CASCADE;
DROP TABLE IF EXISTS public.data_billing_type        CASCADE;

DROP TABLE IF EXISTS public.family_group             CASCADE;
DROP TABLE IF EXISTS public.family_discount_policy   CASCADE;
DROP TABLE IF EXISTS public.contract_discount        CASCADE;

-- 1) 계약(선택약정) 할인 정책
CREATE TABLE public.contract_discount
(
    discount_percent numeric(5, 4) NOT NULL,
    duration_months  integer       NOT NULL PRIMARY KEY,
    CONSTRAINT ck_contract_discount_percent
        CHECK (discount_percent >= 0 AND discount_percent <= 1)
);

COMMENT ON TABLE public.contract_discount IS '선택 약정 할인 정책';


-- 2) 무제한 여부 종류
CREATE TABLE public.data_billing_type
(
    data_billing_type_code varchar(10) NOT NULL PRIMARY KEY,
    data_billing_type_name varchar(50) NOT NULL UNIQUE
);

COMMENT ON TABLE public.data_billing_type IS '무제한 여부 종류';
COMMENT ON COLUMN public.data_billing_type.data_billing_type_code IS '무제한 데이터 코드';


-- 3) 가족 결합 할인 정책
CREATE TABLE public.family_discount_policy
(
    max_joined_year_sum    integer,
    max_monthly_amount_sum integer,
    min_joined_year_sum    integer     NOT NULL,
    min_monthly_amount_sum integer     NOT NULL,
    min_user_count         integer     NOT NULL,
    total_discount_amount  integer     NOT NULL,
    policy_code            varchar(20) NOT NULL PRIMARY KEY,
    policy_name            varchar(50) NOT NULL
);

COMMENT ON TABLE public.family_discount_policy IS '가족 결합 할인 정책';
COMMENT ON COLUMN public.family_discount_policy.max_joined_year_sum IS '구성원 합산 가입 년수 끝 값';
COMMENT ON COLUMN public.family_discount_policy.max_monthly_amount_sum IS '가족 구성원 월 이용 총액 기준 끝 값';
COMMENT ON COLUMN public.family_discount_policy.min_joined_year_sum IS '구성원 합산 가입 년수 시작 값';
COMMENT ON COLUMN public.family_discount_policy.min_monthly_amount_sum IS '가족 구성원 월 이용 총액 기준 시작 값';
COMMENT ON COLUMN public.family_discount_policy.min_user_count IS '최소 필요 구성원 수';
COMMENT ON COLUMN public.family_discount_policy.total_discount_amount IS '총 할인 금액';
COMMENT ON COLUMN public.family_discount_policy.policy_code IS '가족 결합 정책 식별자';
COMMENT ON COLUMN public.family_discount_policy.policy_name IS '가족 결합 할인 정책 이름';


-- 4) 가족 그룹
CREATE TABLE public.family_group
(
    status          boolean                     NOT NULL,
    created_at      timestamp(6) with time zone NOT NULL,
    disbanded_at    timestamp(6) with time zone,
    family_group_id bigint generated by default as identity PRIMARY KEY
);

COMMENT ON TABLE public.family_group IS '가족 결합 그룹';
COMMENT ON COLUMN public.family_group.status IS '가족 상태';
COMMENT ON COLUMN public.family_group.created_at IS '생성 날짜';
COMMENT ON COLUMN public.family_group.disbanded_at IS '해지 날짜';
COMMENT ON COLUMN public.family_group.family_group_id IS '가족 식별자';


-- 5) 네트워크 종류
CREATE TABLE public.network_type
(
    network_type_code varchar(10) NOT NULL PRIMARY KEY,
    network_type_name varchar(10) NOT NULL
);

COMMENT ON TABLE public.network_type IS '네트워크 종류';
COMMENT ON COLUMN public.network_type.network_type_code IS '네트워크 종류 코드';
COMMENT ON COLUMN public.network_type.network_type_name IS '네트워크 이름';


-- 6) 부가 서비스 종류(코드 테이블)
CREATE TABLE public.option_service
(
    option_service_code varchar(10) NOT NULL PRIMARY KEY,
    option_service_name varchar(20) NOT NULL UNIQUE
);

COMMENT ON TABLE public.option_service IS '부가 서비스 종류';
COMMENT ON COLUMN public.option_service.option_service_code IS '부가 서비스 종류 식별자';
COMMENT ON COLUMN public.option_service.option_service_name IS '부가 서비스 종류 이름';


-- 7) 복지 할인 정책(코드 테이블)
CREATE TABLE public.welfare_discount
(
    discount_rate numeric(5, 4) NOT NULL,
    max_discount  integer,
    welfare_code  varchar(10)   NOT NULL PRIMARY KEY,
    welfare_name  varchar(30)   NOT NULL,
    CONSTRAINT ck_welfare_discount_rate
        CHECK (discount_rate >= 0 AND discount_rate <= 1)
);

COMMENT ON TABLE public.welfare_discount IS '복지 할인 정책';
COMMENT ON COLUMN public.welfare_discount.discount_rate IS '할인율';
COMMENT ON COLUMN public.welfare_discount.max_discount IS '할인 상한액';
COMMENT ON COLUMN public.welfare_discount.welfare_code IS '복지 할인 정책';
COMMENT ON COLUMN public.welfare_discount.welfare_name IS '복지 종류';


-- 8) 요금제
CREATE TABLE public.plan
(
    excess_charge_per_mb   numeric(5, 4) NOT NULL,
    included_data_mb       integer       NOT NULL,
    is_military_eligible   boolean       NOT NULL,
    monthly_price          integer       NOT NULL,
    data_billing_type_code varchar(10)   NOT NULL,
    network_type_code      varchar(10)   NOT NULL,
    plan_code              varchar(10)   NOT NULL PRIMARY KEY,
    name                   varchar(50)   NOT NULL,
    info                   text          NOT NULL,

    CONSTRAINT fk_plan_data_billing_type
        FOREIGN KEY (data_billing_type_code)
            REFERENCES public.data_billing_type (data_billing_type_code),

    CONSTRAINT fk_plan_network_type
        FOREIGN KEY (network_type_code)
            REFERENCES public.network_type (network_type_code)
);

COMMENT ON TABLE public.plan IS '요금제';
COMMENT ON COLUMN public.plan.excess_charge_per_mb IS '초과 데이터 MB당 요금';
COMMENT ON COLUMN public.plan.included_data_mb IS '기본 데이터 제공량';
COMMENT ON COLUMN public.plan.is_military_eligible IS '군인 요금제 여부';
COMMENT ON COLUMN public.plan.monthly_price IS '월 비용';
COMMENT ON COLUMN public.plan.data_billing_type_code IS '무제한 데이터 코드';
COMMENT ON COLUMN public.plan.network_type_code IS '네트워크 종류 코드';
COMMENT ON COLUMN public.plan.plan_code IS '요금제 식별자';
COMMENT ON COLUMN public.plan.name IS '요금제 이름';
COMMENT ON COLUMN public.plan.info IS '요금제 설명';


-- 9) 부가 서비스 가격 정책(이력)
CREATE TABLE public.option_policy_history
(
    effective_from      timestamp(6) with time zone NOT NULL,
    effective_to        timestamp(6) with time zone NOT NULL,
    monthly_price       bigint                      NOT NULL,
    option_history_id   bigint generated by default as identity PRIMARY KEY,
    option_service_code varchar(10)                 NOT NULL,

    CONSTRAINT uk_option_policy_history_service_from
        UNIQUE (option_service_code, effective_from),

    CONSTRAINT ck_option_policy_history_range
        CHECK (effective_from < effective_to),

    CONSTRAINT fk_option_policy_history_option_service
        FOREIGN KEY (option_service_code)
            REFERENCES public.option_service (option_service_code)
);

COMMENT ON TABLE public.option_policy_history IS '부가 서비스 가격 정책';
COMMENT ON COLUMN public.option_policy_history.effective_from IS '적용 시작일';
COMMENT ON COLUMN public.option_policy_history.effective_to IS '적용 종료일';
COMMENT ON COLUMN public.option_policy_history.monthly_price IS '월 가격';
COMMENT ON COLUMN public.option_policy_history.option_history_id IS '부가 서비스 식별자';
COMMENT ON COLUMN public.option_policy_history.option_service_code IS '부가 서비스 코드';


-- 10) 요금제 기본 제공 서비스(매핑)
CREATE TABLE public.plan_included_option
(
    plan_option_id      bigint generated by default as identity PRIMARY KEY,
    option_service_code varchar(10) NOT NULL,
    plan_code           varchar(10) NOT NULL,

    CONSTRAINT uk_plan_included_option_plan_option
        UNIQUE (plan_code, option_service_code),

    CONSTRAINT fk_plan_included_option_option_service
        FOREIGN KEY (option_service_code)
            REFERENCES public.option_service (option_service_code),

    CONSTRAINT fk_plan_included_option_plan
        FOREIGN KEY (plan_code)
            REFERENCES public.plan (plan_code)
);

COMMENT ON TABLE public.plan_included_option IS '요금제 기본 제공 서비스';
COMMENT ON COLUMN public.plan_included_option.plan_option_id IS '요금제 기본 제공 부가 서비스 식별자';
COMMENT ON COLUMN public.plan_included_option.option_service_code IS '부가 서비스 FK';
COMMENT ON COLUMN public.plan_included_option.plan_code IS '요금제 FK';


-- 11) 유저
CREATE TABLE public.users
(
    birth_date   date                        NOT NULL,
    is_welfare   integer,
    join_date    date                        NOT NULL,
    created_at   timestamp(6) with time zone NOT NULL,
    modified_at  timestamp(6) with time zone NOT NULL,
    user_id      bigint                      NOT NULL PRIMARY KEY,
    name         varchar(10)                 NOT NULL,
    plan_code    varchar(10)                 ,
    welfare_code varchar(10)                 ,
    phone_number varchar(20)                 NOT NULL UNIQUE,
    user_role    varchar(255)                NOT NULL
        CONSTRAINT users_user_role_check
            CHECK ((user_role)::text = ANY
                   ((ARRAY ['ADMIN'::character varying, 'GUEST'::character varying, 'USER'::character varying])::text[])),
    user_status  varchar(255)                NOT NULL
        CONSTRAINT users_user_status_check
            CHECK ((user_status)::text = ANY
                   ((ARRAY ['ACTIVE'::character varying, 'WITHDRAWN'::character varying, 'BANNED'::character varying])::text[])),

    CONSTRAINT fk_users_plan
        FOREIGN KEY (plan_code)
            REFERENCES public.plan (plan_code),

    CONSTRAINT fk_users_welfare_discount
        FOREIGN KEY (welfare_code)
            REFERENCES public.welfare_discount (welfare_code)
);

COMMENT ON TABLE public.users IS '유저';
COMMENT ON COLUMN public.users.birth_date IS '유저 생년월일';
COMMENT ON COLUMN public.users.is_welfare IS '복지 대상 여부';
COMMENT ON COLUMN public.users.join_date IS '유저 가입일';
COMMENT ON COLUMN public.users.created_at IS '유저 생성일';
COMMENT ON COLUMN public.users.modified_at IS '유저 수정일';
COMMENT ON COLUMN public.users.user_id IS '유저 식별값';
COMMENT ON COLUMN public.users.name IS '유저 이름';
COMMENT ON COLUMN public.users.plan_code IS '요금제 코드';
COMMENT ON COLUMN public.users.welfare_code IS '복지 할인 코드';
COMMENT ON COLUMN public.users.phone_number IS '유저 전화번호';
COMMENT ON COLUMN public.users.user_role IS '유저 권한';
COMMENT ON COLUMN public.users.user_status IS '유저 상태';


-- 12) 유저 선택 약정
CREATE TABLE public.user_contract
(
    end_date         date   NOT NULL,
    start_date       date   NOT NULL,
    user_contract_id bigint generated by default as identity PRIMARY KEY,
    user_id          bigint NOT NULL,

    CONSTRAINT ck_user_contract_range
        CHECK (start_date < end_date),

    CONSTRAINT fk_user_contract_user
        FOREIGN KEY (user_id)
            REFERENCES public.users (user_id)
);

COMMENT ON TABLE public.user_contract IS '유저 선택 약정';
COMMENT ON COLUMN public.user_contract.end_date IS '종료일';
COMMENT ON COLUMN public.user_contract.start_date IS '시작일';
COMMENT ON COLUMN public.user_contract.user_contract_id IS '유저 선택 약정 식별자';
COMMENT ON COLUMN public.user_contract.user_id IS '유저 FK';


-- 13) 유저 직접 구독 부가 서비스
CREATE TABLE public.user_option_subscription
(
    end_date            timestamp(6) with time zone NOT NULL,
    start_date          timestamp(6) with time zone NOT NULL,
    user_id             bigint                      NOT NULL,
    user_option_id      bigint generated by default as identity PRIMARY KEY,
    option_service_code varchar(10)                 NOT NULL,

    CONSTRAINT ck_user_option_subscription_range
        CHECK (start_date < end_date),

    CONSTRAINT fk_user_option_subscription_user
        FOREIGN KEY (user_id)
            REFERENCES public.users (user_id),

    CONSTRAINT fk_user_option_subscription_option_service
        FOREIGN KEY (option_service_code)
            REFERENCES public.option_service (option_service_code)
);

COMMENT ON TABLE public.user_option_subscription IS '유저 직접 구독 부가 서비스';
COMMENT ON COLUMN public.user_option_subscription.end_date IS '구독 만료일';
COMMENT ON COLUMN public.user_option_subscription.start_date IS '구독 시작일';
COMMENT ON COLUMN public.user_option_subscription.user_id IS '유저 FK';
COMMENT ON COLUMN public.user_option_subscription.user_option_id IS '유저 직접 구독 부가 서비스 식별자';
COMMENT ON COLUMN public.user_option_subscription.option_service_code IS '부가 서비스 코드';


-- 14) 사용자 요금제(이력)
CREATE TABLE public.user_plans
(
    end_date     timestamp(6) with time zone NOT NULL,
    start_date   timestamp(6) with time zone NOT NULL,
    user_id      bigint                      NOT NULL,
    user_plan_id bigint generated by default as identity PRIMARY KEY,
    plan_code    varchar(10)                 NOT NULL,

    CONSTRAINT ck_user_plans_range
        CHECK (start_date < end_date),

    CONSTRAINT fk_user_plans_user
        FOREIGN KEY (user_id)
            REFERENCES public.users (user_id),

    CONSTRAINT fk_user_plans_plan
        FOREIGN KEY (plan_code)
            REFERENCES public.plan (plan_code)
);

COMMENT ON TABLE public.user_plans IS '사용자 요금제';
COMMENT ON COLUMN public.user_plans.end_date IS '요금제 만료일';
COMMENT ON COLUMN public.user_plans.start_date IS '요금제 가입일';
COMMENT ON COLUMN public.user_plans.user_id IS '유저 FK';
COMMENT ON COLUMN public.user_plans.user_plan_id IS '사용자 요금제 식별자';
COMMENT ON COLUMN public.user_plans.plan_code IS '요금제 코드';


-- 15) 유저 군인 정보
CREATE TABLE public.user_soldier
(
    end_date        date,
    start_date      date   NOT NULL,
    user_id         bigint NOT NULL UNIQUE,
    user_soldier_id bigint generated by default as identity PRIMARY KEY,

    CONSTRAINT fk_user_soldier_user
        FOREIGN KEY (user_id)
            REFERENCES public.users (user_id)
);

COMMENT ON COLUMN public.user_soldier.end_date IS '전역일';
COMMENT ON COLUMN public.user_soldier.start_date IS '입대일';
COMMENT ON COLUMN public.user_soldier.user_id IS '유저 FK';
COMMENT ON COLUMN public.user_soldier.user_soldier_id IS '유저군인 식별자';


-- 16) 가족 그룹 구성원(매핑)
CREATE TABLE public.family_group_user
(
    joined_at       date   NOT NULL,
    left_at         date,
    family_group_id bigint NOT NULL,
    family_user_id  bigint generated by default as identity PRIMARY KEY,
    user_id         bigint NOT NULL,

    CONSTRAINT uk_family_group_user
        UNIQUE (user_id, family_group_id),

    CONSTRAINT fk_family_group_user_family_group
        FOREIGN KEY (family_group_id)
            REFERENCES public.family_group (family_group_id),

    CONSTRAINT fk_family_group_user_user
        FOREIGN KEY (user_id)
            REFERENCES public.users (user_id)
);

-- 17) 사용자 월별 사용량
CREATE TABLE public.monthly_data_usage (
    data_usage_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    used_data_mb BIGINT NOT NULL,
    usage_aggregated_at TIMESTAMPTZ NOT NULL,

    "usage_year_month" VARCHAR(6) NOT NULL,
    user_id BIGINT NOT NULL,

    CONSTRAINT uk_monthly_data_usage_user_month UNIQUE (user_id, "usage_year_month")
);

COMMENT ON TABLE public.family_group_user IS '가족 결합 그룹-구성원 매핑';
COMMENT ON COLUMN public.family_group_user.joined_at IS '생성 날짜';
COMMENT ON COLUMN public.family_group_user.left_at IS '떠난 날짜';
COMMENT ON COLUMN public.family_group_user.family_user_id IS '가족 구성원 식별자';


