spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/billing}
    username: ${SPRING_DATASOURCE_USERNAME:billing}
    password: ${SPRING_DATASOURCE_PASSWORD:billing}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:false}
    show-sql: ${JPA_SHOW_SQL:false}
